title: The Future is Now
author: Alpharius
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site is dedicated to all people who want to understand that the real world is what was once called science fiction. 
  
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
